name: Build and Push StickC only

on:
  workflow_dispatch:
  pull_request:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Marauder Binaries
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install M5Stack Boards and Compile TestFile
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: TestFile2.ino
          arduino-board-fqbn: m5stack:esp32:m5stack_stickc_plus2
          platform-url: https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json
        
      - name: Pull M5Stack v2.0.10
        uses: actions/checkout@v2
        with:
          repository: m5stack/arduino-esp32
          path: M5StackBoards

      - name: Install AsyncTCP
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomAsyncTCP
          
      - name: Install MicroNMEA
        uses: actions/checkout@v2
        with:
          repository: stevemarple/MicroNMEA
          ref: v2.0.6
          path: CustomMicroNMEA
          
      - name: Install ESPAsyncWebServer
        uses: actions/checkout@v2
        with:
          repository: bigbrodude6119/ESPAsyncWebServer
          ref: master
          path: CustomESPAsyncWebServer
          
      - name: Install TFT_eSPI
        uses: actions/checkout@v2
        with:
          repository: Bodmer/TFT_eSPI
          ref: 2.2.23
          path: CustomTFT_eSPI

      - name: Install lv_arduino
        uses: actions/checkout@v2
        with:
          repository: lvgl/lv_arduino
          ref: 3.0.0
          path: Customlv_arduino

      - name: Install JPEGDecoder
        uses: actions/checkout@v2
        with:
          repository: Bodmer/JPEGDecoder
          ref: 1.8.0
          path: CustomJPEGDecoder

      - name: Install NimBLE-Arduino
        uses: actions/checkout@v2
        with:
          repository: h2zero/NimBLE-Arduino
          ref: 1.2.0
          path: CustomNimBLE-Arduino

      - name: Install Adafruit_NeoPixel
        uses: actions/checkout@v2
        with:
          repository: adafruit/Adafruit_NeoPixel
          ref: 1.10.7
          path: CustomAdafruit_NeoPixel

      - name: Install ArduinoJson
        uses: actions/checkout@v2
        with:
          repository: bblanchon/ArduinoJson
          ref: v6.18.2
          path: CustomArduinoJson

      - name: Install SwitchLib
        uses: actions/checkout@v2
        with:
          repository: justcallmekoko/SwitchLib
          ref: main
          path: CustomSwitchLib
          
      - name: Install LinkedList
        uses: actions/checkout@v2
        with:
          repository: ivanseidel/LinkedList
          ref: v1.3.3
          path: CustomLinkedList
          
      - name: Install EspSoftwareSerial
        uses: actions/checkout@v2
        with:
          repository: plerup/espsoftwareserial
          ref: 8.1.0
          path: CustomEspSoftwareSerial
          
      - name: Configure TFT_eSPI
        run: |
          rm -f CustomTFT_eSPI/User_Setup_Select.h
          cp User_Setup_Select.h CustomTFT_eSPI/
          cp User_Setup_marauder_m5stickcp2.h CustomTFT_eSPI/
          pwd
          ls -la
          ls -la CustomTFT_eSPI

      - name: Install esptool
        run: |
          pip install -U esptool
          
      - name: Modify platform.txt in m5stack boards
        run: |
          echo "Chicken"
          for i in $(find /home/runner/.arduino15/packages/m5stack/hardware/esp32/ -name "platform.txt"); do
            sed -i 's/compiler.c.elf.libs.esp32c3=/compiler.c.elf.libs.esp32c3=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32s3=/compiler.c.elf.libs.esp32s3=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32s2=/compiler.c.elf.libs.esp32s2=-zmuldefs /' "$i"
            sed -i 's/compiler.c.elf.libs.esp32=/compiler.c.elf.libs.esp32=-zmuldefs /' "$i"
            cat "$i" | grep compiler.c.elf.libs.esp32c3
            cat "$i" | grep compiler.c.elf.libs.esp32s3
            cat "$i" | grep compiler.c.elf.libs.esp32s2
            cat "$i" | grep compiler.c.elf.libs.esp32
          done
          
      - name: Build Marauder for Marauder M5StickC Plus 2
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: esp32_marauder.ino
          arduino-board-fqbn: m5stack:esp32:m5stack_stickc_plus2:PartitionScheme=min_spiffs
          extra-arduino-cli-args: "--warnings none"
          
      - name: Create Complete Firmware Binary (Bootloader/Partitions/App)
        run: |
          set -x
          esptool.py --chip esp32 merge_bin --output esp32_marauder.m5stickc_plus2_Complete.bin \
              0x1000 esp32_marauder/build/m5stack.esp32.m5stack_stickc_plus2/esp32_marauder.ino.partitions.bin \
              0x8000 esp32_marauder/build/m5stack.esp32.m5stack_stickc_plus2/esp32_marauder.ino.bootloader.bin \
              0x10000 esp32_marauder/build/m5stack.esp32.m5stack_stickc_plus2/esp32_marauder.ino.bin

      - name: Rename Marauder M5StickC plus 2 bin
        run: |
          mv ./esp32_marauder/build/m5stack.esp32.m5stack_stickc_plus2/esp32_marauder.ino.bin ./esp32_marauder/build/m5stack.esp32.m5stack_stickc_plus2/esp32_marauder.m5stickc_plus2.bin
        
        # Uncomment next line to export .elf for debugging
        #  mv ./esp32_marauder/build/m5stack.esp32.m5stack_stickc_plus2/esp32_marauder.ino.elf ./esp32_marauder/build/m5stack.esp32.m5stack_stickc_plus2/esp32_marauder.m5stickc_plus2.elf



      - name: Display finished bins
        run: |
          find ./esp32_marauder/build -name "*.bin"
          

      - name: 'Upload Marauder M5StickC Plus 2 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: esp32_marauder.m5stickc_plus2.bin
          path: ./esp32_marauder/build/m5stack.esp32.m5stack_stickc_plus2/esp32_marauder.m5stickc_plus2*.bin
          retention-days: 5
          
